version: "3.7"

services:

  go-react:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: go-react
    #command: bash -c /usr/local/bin/go-react
    expose:
      - "9000"
      - "3000"
    ports:
      - "9000:9000"
      - "3000:3000"
    networks:
      - go_react-network-prod

networks:
  go_react-network-prod: