version: '3.4'

services:

    # This is an example to support container based
    # tesing. Replace this with a version appropriate
    # for your project.
    goreact:
        image: ${APP_IMAGE_NAME}:${APP_IMAGE_TAG}
        container_name: goreact
        command: ["/${APP_NAME}"]
        ports:
            - 80:80
        networks:
            - goweb_e2e_network

# Replace network name 
networks:
    goweb_e2e_network: