version: '3.4'

services:

    router:
        image: binocarlos/noxy
        ports:
            - 80:80
        container_name: router
        environment:
            - NOXY_DEFAULT_HOST=react
            - NOXY_DEFAULT_PORT=3030
            - NOXY_DEFAULT_WS=1
            - NOXY_API_FRONT=/api
            - NOXY_API_HOST=rest
            - NOXY_API_PORT=9000
        networks:
            - goweb_dev_network

    react:
        image: ${REACT_IMAGE_NAME}:${IMAGE_TAG}
        container_name: react
        expose:
            - 3030
        ports:
            - 3030:3030
        volumes:
            - ../../web/reactjs/src:/opt/src
            - ../../web/reactjs/webpack:/opt/webpack
            - ../../web/reactjs/.babelrc:/opt/.babelrc
            - ../../web/reactjs/images:/opt/images
            - ../..//web/reactjs/.eslintrc.json:/opt/.eslintrc.json
        networks:
            - goweb_dev_network

    rest:
        image: ${REST_IMAGE_NAME}:${IMAGE_TAG}
        command: ["/usr/local/bin/${REST_SERVER_NAME}"]
        container_name: rest
        expose:
            - 9000
        ports:
            - 9000:9000
        networks:
            - goweb_dev_network

# Replace network name 
networks:
    goweb_dev_network:
