version: "3.7"

services:

  development:
    build:
      context: ../
      dockerfile: Dockerfile
      target: development
    image: ${DEV_IMAGE_NAME}:${IMAGE_TAG}

  production:
    build:
      context: ../
      dockerfile: Dockerfile
    image: ${PROD_IMAGE_NAME}:${IMAGE_TAG}
  