name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      # - run: ./scripts/production/build.sh container
      # - run: ./scripts/production/build.sh native
      # - uses: actions/upload-artifact@v1
      #   with:
      #     name: native-go-web
      #     path: ./build/native

