name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/production/build.sh container
      - run: ./scripts/production/build.sh native

